

const GALACTUS_AGENT_API = process.env.GALACTUS_AGENT_API ? process.env.GALACTUS_AGENT_API : "http://agent:7867"

const PUBLIC_GALACTUS_AGENT_API = process.env.NEXT_PUBLIC_GALACTUS_AGENT_API ? process.env.NEXT_PUBLIC_GALACTUS_AGENT_API : "http://localhost:7867"

export { GALACTUS_AGENT_API, PUBLIC_GALACTUS_AGENT_API }
