
name: agent
run-name: Building Galactus Agent Docker Image and Pushing it to DockerHub

on:
  push:
    paths:
      - "**"
      - '!web/**'
jobs:
  build-agent-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          platform:
              - linux/amd64
              - linux/arm64
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: ${{ matrix.platform }}
          tags: mubashiro/galactus-agent:latest
